project:
  type: website
  output-dir: docs

website:
  title: "Tomer"
  navbar:
    background: "#c76767"
    search: true
    left:
      - text: "About me"
        file: index.qmd
      - text: "Posts"
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/tomerzipori
      - icon: twitter
        href: https://twitter.com/ZiporiTomer
      - icon: linkedin
        href: www.linkedin.com/in/tomer-zipori
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

