project:
  type: website
  output-dir: docs

website:
  site-url: https://tomerzipori.github.io/blog/
  title: "Tomer's stats blog"
  favicon: "static/favicon.png"
  description: ""
  twitter-card:
    creator: "@tomerzipori"
    title: "Tomer's stats blog"
    description: "Posting about more and less interesting things I learn"
    card-style: "summary"
  search: false
  open-graph:
    site-name:  "Tomer's stats blog"
    description: "Posting about more and less interesting things I learn"
    image: ""
  navbar:
    logo: "static/favicon.png"
    title: "Tomer's stats blog"
    background: primary
    search: true
    left:
      - text: "About me"
        file: index.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "CV"
        file: cv.html
    right:
      - icon: github
        href: https://github.com/tomerzipori
      - icon: twitter
        href: https://twitter.com/ZiporiTomer
      - icon: rss
        href: blog.xml
  page-footer:
    left: "© 2025 Tomer Zipori | Part of the [R-Bloggers](https://www.r-bloggers.com/) network"
    center: "powered by [quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/tomerzipori
      - icon: twitter
        href: https://twitter.com/ZiporiTomer
      - icon: linkedin
        href: https://www.linkedin.com/in/tomer-zipori/
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css:
      - styles.css
      - academicons.css
    toc: true
    execute:
      freeze: auto

editor: visual

